"""add professional deletion improvements fields

Revision ID: 23f6c23e1f1b
Revises: 1374f3c565ad
Create Date: 2025-11-01 18:32:18.432980

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "23f6c23e1f1b"
down_revision: str | None = "1374f3c565ad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "professionals",
        sa.Column(
            "under_investigation",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
            comment="Professionnel sous enquête médico-légale (bloque suppression)",
        ),
    )
    op.add_column(
        "professionals",
        sa.Column(
            "investigation_notes",
            sa.String(length=1000),
            nullable=True,
            comment="Notes sur l'enquête en cours",
        ),
    )
    op.add_column(
        "professionals",
        sa.Column(
            "correlation_hash",
            sa.String(length=64),
            nullable=True,
            comment="Hash SHA-256 de email+professional_id pour corrélation anonymisée",
        ),
    )
    op.add_column(
        "professionals",
        sa.Column(
            "soft_deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Date de soft delete (début période de grâce 7 jours)",
        ),
    )
    op.add_column(
        "professionals",
        sa.Column(
            "anonymized_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Date d'anonymisation définitive (après période de grâce)",
        ),
    )
    op.alter_column(
        "professionals",
        "deleted_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Date de suppression définitive (deprecated, use soft_deleted_at)",
        existing_comment="Date de suppression (soft delete)",
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_professionals_anonymized_at"), "professionals", ["anonymized_at"], unique=False
    )
    op.create_index(
        op.f("ix_professionals_correlation_hash"),
        "professionals",
        ["correlation_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_professionals_soft_deleted_at"), "professionals", ["soft_deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_professionals_under_investigation"),
        "professionals",
        ["under_investigation"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_professionals_under_investigation"), table_name="professionals")
    op.drop_index(op.f("ix_professionals_soft_deleted_at"), table_name="professionals")
    op.drop_index(op.f("ix_professionals_correlation_hash"), table_name="professionals")
    op.drop_index(op.f("ix_professionals_anonymized_at"), table_name="professionals")
    op.alter_column(
        "professionals",
        "deleted_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Date de suppression (soft delete)",
        existing_comment="Date de suppression définitive (deprecated, use soft_deleted_at)",
        existing_nullable=True,
    )
    op.drop_column("professionals", "anonymized_at")
    op.drop_column("professionals", "soft_deleted_at")
    op.drop_column("professionals", "correlation_hash")
    op.drop_column("professionals", "investigation_notes")
    op.drop_column("professionals", "under_investigation")
    # ### end Alembic commands ###
