"""add patient deletion improvements fields

Revision ID: 334ba84e6c89
Revises: 23f6c23e1f1b
Create Date: 2025-11-14 00:15:39.445902

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "334ba84e6c89"
down_revision: str | None = "23f6c23e1f1b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "patients",
        sa.Column(
            "under_investigation",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
            comment="Patient sous enquête (bloque suppression)",
        ),
    )
    op.add_column(
        "patients",
        sa.Column(
            "investigation_notes",
            sa.String(length=1000),
            nullable=True,
            comment="Notes sur l'enquête en cours",
        ),
    )
    op.add_column(
        "patients",
        sa.Column(
            "correlation_hash",
            sa.String(length=64),
            nullable=True,
            comment="Hash SHA-256 de email+national_id pour corrélation anonymisée",
        ),
    )
    op.add_column(
        "patients",
        sa.Column(
            "soft_deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Date de soft delete (début période de grâce 7 jours)",
        ),
    )
    op.add_column(
        "patients",
        sa.Column(
            "anonymized_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Date d'anonymisation définitive (après période de grâce)",
        ),
    )
    op.alter_column(
        "patients",
        "deleted_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Date de suppression définitive (deprecated, use soft_deleted_at)",
        existing_comment="Date de suppression (soft delete)",
        existing_nullable=True,
    )
    op.create_index(op.f("ix_patients_anonymized_at"), "patients", ["anonymized_at"], unique=False)
    op.create_index(
        op.f("ix_patients_correlation_hash"), "patients", ["correlation_hash"], unique=False
    )
    op.create_index(
        op.f("ix_patients_soft_deleted_at"), "patients", ["soft_deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_patients_under_investigation"), "patients", ["under_investigation"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_patients_under_investigation"), table_name="patients")
    op.drop_index(op.f("ix_patients_soft_deleted_at"), table_name="patients")
    op.drop_index(op.f("ix_patients_correlation_hash"), table_name="patients")
    op.drop_index(op.f("ix_patients_anonymized_at"), table_name="patients")
    op.alter_column(
        "patients",
        "deleted_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Date de suppression (soft delete)",
        existing_comment="Date de suppression définitive (deprecated, use soft_deleted_at)",
        existing_nullable=True,
    )
    op.drop_column("patients", "anonymized_at")
    op.drop_column("patients", "soft_deleted_at")
    op.drop_column("patients", "correlation_hash")
    op.drop_column("patients", "investigation_notes")
    op.drop_column("patients", "under_investigation")
    # ### end Alembic commands ###
